### ISSUE TITLE
Add the SharedBanner to this project.

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/firefox-svg-icons#1]
We “just” need to [include](https://github.com/FirefoxUX/StyleGuide/blob/gh-pages/index.html#L15) `https://github.com/FirefoxUX/StyleGuide/blob/gh-pages/index.html#L15` and make sure the sticky search bar is [~50px lower](https://github.com/FirefoxUX/StyleGuide/blob/gh-pages/src/styles/base.scss#L77), I think…  :wink:

**Comment by nt1m** [comment]
Not a fan of how it looks, but done !
