### ISSUE TITLE
Make sure we have all the icons from this font…

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/firefox-svg-icons#7]
https://youwenliang.github.io/Firefox_Icon-Fonts/

(Created by @mark.liang from the Taipei office!  🙂)

**Comment by nt1m** [comment]
@bwinton I've added a bunch, can you check if everything looks alright ?

**Comment by bwinton** [comment]
Sure…  Is there a pull request I should be looking at?

**Comment by nt1m** [comment]
@bwinton everything is live http://firefoxux.github.io/firefox-svg-icons/viewer/

**Comment by bwinton** [comment]
Ah, yes…  I checked the commits, and it all looks good to me.  They even show up in the embed.html…  😄  (Feel free to close this if they're all added.)
