### ISSUE TITLE
Glyph issue: debugger toggleBreakpoints

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/firefox-svg-icons#9]
The Glyph for the debugger toggleBreakpoints doesn't seem readable to me in the list of glyphs. Is the SVG displaying properly? 

http://i.sevaan.com/180T2m2O0j1g

**Comment by nt1m** [comment]
Good catch! The image is currently a sprite, but it should be split into 2 images. Going to remove it for now.

**Comment by nt1m** [comment]
Fixed by 0d39d8c94e971d8046ff286cd0ede940dcbf7639
